final_project/bartini/config/routes.rb
Rails.application.routes.draw do
  # General Application Routes
  root to: 'sessions#new'

  get 'index', to: 'dashboard#index', as: 'index'

  post 'dashboard/sign_in' 

  get 'new', to: 'registration#new', as: 'registration_page'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "register" => "user_accounts#new", :as => "register"

  resources :user_accounts
  resources :sessions

  # Main Application Routes
  get 'prepare_drink', to: 'drink_management#prepare_drink', as: 'prepare_drink'
  post 'create_drink', to: 'drink_management#create_drink', as: 'create_drink'

  post 'add_ingredient', to: 'drink_management#add_ingredient', as: 'add_ingredient'
  post 'save_changes', to: 'drink_management#save_changes', as: 'save_changes'
  get 'edit_ingredients/:drink_id', to: 'drink_management#edit_ingredients', as: 'edit_ingredients' 
  post 'update_description', to: 'drink_management#update_description', as: 'update_description'
  get 'remove_ingredient/:drink_id/:ingredient_id', to: 'drink_management#remove_ingredient', as: 'remove_ingredient'
  post 'upload_file', to: 'drink_management#upload_file', as: 'upload_file'
  
  get 'drink_page/:drink_id', to: 'drink_management#drink_page', as: 'drink_page'

end

final_project/bartini/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	def index
		@list_of_drinks = Drink.all
	end

  def datafile(drink_id)
    DataStorage.find_by(drink_id: drink_id)
  end



end

final_project/bartini/app/views/dashboard/index.html.erb
<h1> Welcome to Bartini </h1>

<table>
	<% @list_of_drinks.each do |i| %>
		<% if ( (current_user.id == i.user_account_id) && i.visibility ) || !i.visibility %>
			<tr> 
				<div>
					<%= link_to "#{i.drink_name}", drink_page_path(i.id) %>
				</div>
				<div>
					<% if datafile(i.id) %>
						<%= image_tag "/assets/images/#{datafile(i.id).original_filename}", :alt => "#{datafile(i.id).original_filename}" %>
					<% else %>
						<%= image_tag "/assets/images/static_drink.jpg", :alt => "static_drink.jpg" %>
					<% end %>
				</div>
			</tr>
		<% end %>
	<% end %>
</table>

<%= link_to 'Create Drink', prepare_drink_path %>